class Features {
    constructor( additionalFeatures, aho, appConnectivity, battery, brakeLight, clock,
        digitalFuelGuage, drl, frontStorageBox, fuelGuage, gpsNavigation, headlightType,
        killSwitch, lowBatteryIndicator, lowFuelIndicator, lowOilIndicator, numberOfTripmeters,
        odometer, passLight, pillionBackrest, pillionFootrest, pillionGrabrail, pillionSeat,
        shiftLight, speedometer, standAlarm, startType, steppedSeat, tachometer, tripmeterType,
        turnSignal, underSeatStorage, usbChargingPort ) {
        this.additionalFeatures = additionalFeatures,
        this.aho = aho,
        this.appConnectivity = appConnectivity,
        this.battery = battery,
        this.brakeLight = brakeLight,
        this.clock = clock,
        this.digitalFuelGuage = digitalFuelGuage,
        this.drl = drl,
        this.frontStorageBox = frontStorageBox,
        this.fuelGuage = fuelGuage,
        this.gpsNavigation = gpsNavigation,
        this.headlightType = headlightType,
        this.killSwitch = killSwitch,
        this.lowBatteryIndicator = lowBatteryIndicator,
        this.lowFuelIndicator = lowFuelIndicator,
        this.lowOilIndicator = lowOilIndicator,
        this.numberOfTripmeters = numberOfTripmeters,
        this.odometer = odometer,
        this.passLight = passLight,
        this.pillionBackrest = pillionBackrest,
        this.pillionFootrest = pillionFootrest,
        this.pillionGrabrail = pillionGrabrail,
        this.pillionSeat = pillionSeat,
        this.shiftLight = shiftLight,
        this.speedometer = speedometer,
        this.standAlarm = standAlarm,
        this.startType = startType,
        this.steppedSeat = steppedSeat,
        this.tachometer = tachometer,
        this.tripmeterType = tripmeterType,
        this.turnSignal = turnSignal,
        this.underSeatStorage = underSeatStorage,
        this.usbChargingPort = usbChargingPort
    }
}

module.exports = Features;